default_platform(:android)

  desc "Distribuir APK en Firebase"
  lane :firebase_beta do
    gradle(
      task: "assemble",
      build_type: "Release"
    )

    firebase_app_distribution(
      app: "1:1073939308683:android:9b25609d00684a7ce3348e",
      service_credentials_file: "credentials.json",
      testers: "enriquezjavier.developer@gmail.com",
      release_notes: "Versión de prueba desde Fastlane")
end